[package]
name = "beacon-verifier"
version = "0.1.2"
authors = ["Mr.Robb <roberto.ariosa@crg.eu>"]
edition = "2018"
license = "Apache-2.0"
description = "Compliance tool to verify beacon implementations."
repository = "https://github.com/ga4gh-beacon/beacon-verifier"
keywords = ["genetics", "http", "api", "jsonschema", "validation"]
categories = ["development-tools::testing"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Config
clap = { version = "3.0.0-beta", features = ["yaml"] }

# Filesystem
walkdir = "2.3.2"
tempfile = "3.2.0"
git2 = "0.13"

# Validation
jsonschema = { version = "0.11.0", features = ["reqwest"] }
url = { version = "2.2.2", features = ["serde"] }
regex = "1.5.4"
ureq = { version = "2.1.1", features = ["json", "charset"] }

# Output
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Log
log = "0.4.0"
pretty_env_logger = "0.4.0"
