[package]
name = "jsc-val"
version = "0.1.0"
authors = ["Mr.Robb <roberto.ariosa@crg.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Config
clap = { version = "3.0.0-beta", features = ["yaml"] }

# Directory
walkdir = "2.3.2"

# Validation
valico = "3.6.0"
url = "2.2.2"
serde_json = "1.0"
regex = "1.5.4"

# Log
paris = { version = "1.5", features = ["no_logger", "macros"] }